"""Interpretable belief-dynamics baselines — the CFI-005 reference package.

`COMPUTATIONAL_FINANCE_OF_INTELLIGENCE.md` §2.1 proposes one model family for
belief in log-odds,

```text
dl = mu(l, e, f) dt + sigma(l, e, f) dW + J dN
```

and then says something easy to skip past: *this equation is a model family and
research hypothesis, not a claim that human or machine beliefs actually follow a
diffusion.* This module takes that seriously. It implements the four
interpretable members the bridge starts from, each with a simulator and an
estimator, and it exists to answer one question before any subject is observed:
**when the data really were generated by one of these, does the estimator
recover the parameters that generated them?**

That question has an answer that can be wrong, which is the entire point.
:func:`recovery_study` runs the loop — simulate at known parameters, fit, compare
— and reports the error rather than asserting a threshold. Thresholds belong to
a preregistered protocol, and no protocol has passed G3.

The four baselines, in the order §2.1 lists them:

1. **Exact Bayesian.** In log-odds, Bayes' rule is addition: each piece of
   evidence contributes its log-likelihood ratio and nothing else. The estimator
   recovers a per-evidence LLR.
2. **Asymmetric Bayesian.** The same, with separate weights on confirming and
   disconfirming evidence. `w+ = w- = 1` is the exact case, so the exact model is
   nested inside this one and the gap is directly readable.
3. **Drift-diffusion and Ornstein-Uhlenbeck.** Belief as a random walk, with and
   without pull toward a level. OU nests the driftless walk at `theta = 0`.
4. **Jump-diffusion.** A diffusion plus occasional discrete revisions.

Everything is pure Python, seeded, and deterministic: the same seed gives the
same trajectory on any machine, which is what makes a recovery study a piece of
evidence rather than an anecdote.
"""

from __future__ import annotations

import math
import random
import statistics
from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from drl_cfi.beliefs import (
    Action,
    BeliefEvent,
    BeliefTrajectory,
    Maturity,
    SubjectKind,
    probability,
)
from drl_cfi.linalg import solve_least_squares

__all__ = [
    "MAX_REPRESENTABLE_LOG_ODDS",
    "AsymmetricBayesianFit",
    "BayesianFit",
    "DiffusionFit",
    "JumpDiffusionFit",
    "OrnsteinUhlenbeckFit",
    "ParameterRecovery",
    "RecoveryReport",
    "SaturatedBeliefError",
    "fit_asymmetric_bayesian",
    "fit_bayesian",
    "fit_diffusion",
    "fit_jump_diffusion",
    "fit_ornstein_uhlenbeck",
    "recovery_study",
    "simulate_asymmetric_bayesian",
    "simulate_bayesian",
    "simulate_diffusion",
    "simulate_jump_diffusion",
    "simulate_ornstein_uhlenbeck",
]

#: The finest resolution a probability report is recorded at. Together with the
#: schema's refusal of 0 and 1, this fixes how extreme a belief can be and still
#: be written down.
REPORT_EPSILON = 1e-9

#: The largest belief magnitude this schema can represent, in log-odds.
#:
#: A simulated log-odds path is unbounded; a recorded probability is not. An
#: earlier version of this module clamped the report to the boundary, which
#: looked harmless and was not: once a path saturates, every later record is the
#: same number, every increment is exactly zero, and the estimators downstream
#: read those zeros as data. In a jump-diffusion recovery study that collapsed
#: the robust scale to a tenth of its true value and flagged 155 of 400
#: increments as jumps. Saturation is now an error, because a belief the
#: instrument cannot represent must not be silently converted into one it can.
MAX_REPRESENTABLE_LOG_ODDS = math.log((1.0 - REPORT_EPSILON) / REPORT_EPSILON)

#: Increments this many robust standard deviations from the diffusive fit are
#: treated as jumps. 4 is conventional and deliberately conservative: missing a
#: jump biases the volatility upward, which is the safer direction for a
#: baseline whose job is to be beaten by a better model.
JUMP_THRESHOLD = 4.0


class SaturatedBeliefError(ValueError):
    """A simulated belief left the range the schema can record."""


def _record(
    path: Sequence[float],
    times: Sequence[float],
    *,
    seed: int,
    evidence_ids: Sequence[str | None] | None = None,
    subject_id: str = "sim-000",
    proposition_id: str = "prop-000",
    code_revision: str = "drl-cfi.baselines",
    config_digest: str = "synthetic",
) -> BeliefTrajectory:
    """Wrap a simulated log-odds path in schema records.

    Simulators return trajectories rather than bare lists so that every path the
    estimators see has already survived the same validation a real record would.
    """
    events = []
    for index, (ell, stamp) in enumerate(zip(path, times, strict=True)):
        if abs(ell) > MAX_REPRESENTABLE_LOG_ODDS:
            raise SaturatedBeliefError(
                f"belief reached log-odds {ell:+.3f} at step {index}, beyond the "
                f"representable +/-{MAX_REPRESENTABLE_LOG_ODDS:.3f}. Recording it "
                f"would pin the report at the boundary and emit zero increments "
                f"that the estimators cannot distinguish from a subject who "
                f"stopped updating. Choose parameters that keep the path in "
                f"range, or shorten the horizon."
            )
        events.append(
            BeliefEvent(
                study_id="cfi-005-recovery",
                run_id=f"seed-{seed}",
                subject_id=subject_id,
                subject_kind=SubjectKind.SIMULATOR,
                model_or_cohort_revision="synthetic-generator",
                task_id="belief-path",
                proposition_id=proposition_id,
                step_index=index,
                event_time=stamp,
                reported_probability=probability(ell),
                action=Action.CONTINUE,
                source_rights_id="synthetic-no-rights-implicated",
                code_revision=code_revision,
                config_digest=config_digest,
                seed=seed,
                maturity=Maturity.SYNTHETIC,
                evidence_id=(
                    evidence_ids[index]
                    if evidence_ids is not None and index < len(evidence_ids)
                    else None
                ),
            )
        )
    return BeliefTrajectory(tuple(events))


def _uniform_times(steps: int, dt: float) -> list[float]:
    return [index * dt for index in range(steps + 1)]


# ---------------------------------------------------------------------------
# 1 and 2. Bayesian updating, exact and asymmetric
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class BayesianFit:
    """Per-evidence log-likelihood ratios recovered from a path."""

    llr_by_evidence: Mapping[str, float]
    residual_scale: float
    observations: int

    def predict(self, evidence_id: str) -> float:
        return self.llr_by_evidence[evidence_id]


@dataclass(frozen=True, slots=True)
class AsymmetricBayesianFit:
    """Separate weights on confirming and disconfirming evidence.

    `confirming_weight == disconfirming_weight == 1` is exact Bayesian updating.
    Departures are readable directly: a confirming weight above one with a
    disconfirming weight below one is the classic asymmetry.
    """

    confirming_weight: float
    disconfirming_weight: float
    residual_scale: float
    observations: int

    @property
    def asymmetry(self) -> float:
        """How far this subject is from exact updating, as a signed gap."""
        return self.confirming_weight - self.disconfirming_weight


def simulate_bayesian(
    nominal_llrs: Sequence[float],
    *,
    seed: int,
    initial_log_odds: float = 0.0,
    report_noise: float = 0.0,
    dt: float = 1.0,
    evidence_ids: Sequence[str] | None = None,
) -> BeliefTrajectory:
    """Exact Bayesian updating: each increment is the evidence's LLR.

    `report_noise` is reporting error, not belief noise — the subject's internal
    posterior is exact and what it says about it is not.
    """
    # S311: a seeded generator is the requirement here, not a weakness — a recovery
    # study is only evidence if it reproduces exactly from its seed.
    rng = random.Random(seed)  # noqa: S311
    ell = initial_log_odds
    path = [ell]
    for llr in nominal_llrs:
        ell = ell + llr
        path.append(ell + (rng.gauss(0.0, report_noise) if report_noise > 0.0 else 0.0))
    ids: list[str | None] = (
        list(evidence_ids)
        if evidence_ids is not None
        else [f"e{index}" for index in range(len(nominal_llrs))]
    )
    return _record(path, _uniform_times(len(nominal_llrs), dt), seed=seed, evidence_ids=ids)


def simulate_asymmetric_bayesian(
    nominal_llrs: Sequence[float],
    *,
    confirming_weight: float,
    disconfirming_weight: float,
    seed: int,
    initial_log_odds: float = 0.0,
    report_noise: float = 0.0,
    dt: float = 1.0,
) -> BeliefTrajectory:
    """Bayesian updating that over- or under-weights by evidence direction."""
    # S311: a seeded generator is the requirement here, not a weakness — a recovery
    # study is only evidence if it reproduces exactly from its seed.
    rng = random.Random(seed)  # noqa: S311
    ell = initial_log_odds
    path = [ell]
    for llr in nominal_llrs:
        weight = confirming_weight if llr > 0.0 else disconfirming_weight
        ell = ell + weight * llr
        path.append(ell + (rng.gauss(0.0, report_noise) if report_noise > 0.0 else 0.0))
    ids: list[str | None] = [f"e{index}" for index in range(len(nominal_llrs))]
    return _record(path, _uniform_times(len(nominal_llrs), dt), seed=seed, evidence_ids=ids)


def fit_bayesian(trajectory: BeliefTrajectory) -> BayesianFit:
    """Recover each evidence item's LLR as the mean increment following it.

    Evidence seen once yields that single increment and a residual of zero,
    which is not evidence of fit. `observations` and `residual_scale` are
    reported so that a reader can see how thin the estimate is.
    """
    increments = trajectory.increments()
    labels = trajectory.evidence_ids()
    grouped: dict[str, list[float]] = {}
    for label, increment in zip(labels, increments, strict=True):
        if label is None:
            continue
        grouped.setdefault(label, []).append(increment)
    if not grouped:
        raise ValueError("no evidence-labelled increments; cannot attribute an LLR")
    estimates = {label: statistics.fmean(values) for label, values in grouped.items()}
    residuals = [
        increment - estimates[label]
        for label, increment in zip(labels, increments, strict=True)
        if label is not None
    ]
    scale = statistics.pstdev(residuals) if len(residuals) > 1 else 0.0
    return BayesianFit(llr_by_evidence=estimates, residual_scale=scale, observations=len(residuals))


def fit_asymmetric_bayesian(
    trajectory: BeliefTrajectory, nominal_llrs: Sequence[float]
) -> AsymmetricBayesianFit:
    """Regress observed increments on the direction-split nominal LLR.

    The two regressors are the positive and negative parts of the nominal LLR,
    so the coefficients are exactly the two weights and no reparameterisation
    stands between the fit and its interpretation.
    """
    increments = trajectory.increments()
    if len(nominal_llrs) != len(increments):
        raise ValueError(
            f"need one nominal LLR per increment; got {len(nominal_llrs)} for "
            f"{len(increments)} increments"
        )
    design = [[max(llr, 0.0), min(llr, 0.0)] for llr in nominal_llrs]
    if all(row[0] == 0.0 for row in design) or all(row[1] == 0.0 for row in design):
        raise ValueError(
            "both confirming and disconfirming evidence are required to separate the two weights"
        )
    confirming, disconfirming = solve_least_squares(design, list(increments))
    residuals = [
        increment - (confirming * row[0] + disconfirming * row[1])
        for row, increment in zip(design, increments, strict=True)
    ]
    scale = statistics.pstdev(residuals) if len(residuals) > 1 else 0.0
    return AsymmetricBayesianFit(
        confirming_weight=confirming,
        disconfirming_weight=disconfirming,
        residual_scale=scale,
        observations=len(increments),
    )


# ---------------------------------------------------------------------------
# 3. Drift-diffusion and Ornstein-Uhlenbeck
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class DiffusionFit:
    """Constant drift and volatility for `dl = mu dt + sigma dW`."""

    drift: float
    volatility: float
    observations: int


@dataclass(frozen=True, slots=True)
class OrnsteinUhlenbeckFit:
    """`dl = theta (m - l) dt + sigma dW`.

    `reversion_rate` at zero is the driftless random walk, so the driftless case
    is nested and the estimate says how far from it the data sit.
    """

    reversion_rate: float
    level: float
    volatility: float
    observations: int

    @property
    def half_life(self) -> float:
        """Time for a displacement to decay by half. Infinite when theta <= 0."""
        if self.reversion_rate <= 0.0:
            return math.inf
        return math.log(2.0) / self.reversion_rate


def simulate_diffusion(
    *,
    drift: float,
    volatility: float,
    steps: int,
    dt: float,
    seed: int,
    initial_log_odds: float = 0.0,
) -> BeliefTrajectory:
    """Brownian motion with drift, in log-odds."""
    # S311: a seeded generator is the requirement here, not a weakness — a recovery
    # study is only evidence if it reproduces exactly from its seed.
    rng = random.Random(seed)  # noqa: S311
    scale = volatility * math.sqrt(dt)
    ell = initial_log_odds
    path = [ell]
    for _ in range(steps):
        ell = ell + drift * dt + rng.gauss(0.0, scale)
        path.append(ell)
    return _record(path, _uniform_times(steps, dt), seed=seed)


def simulate_ornstein_uhlenbeck(
    *,
    reversion_rate: float,
    level: float,
    volatility: float,
    steps: int,
    dt: float,
    seed: int,
    initial_log_odds: float = 0.0,
) -> BeliefTrajectory:
    """Mean-reverting belief, simulated with the exact transition law.

    The exact law is used rather than an Euler step so that the simulator is not
    quietly making the same discretisation approximation as the estimator. If it
    did, the recovery study would be measuring the estimator against its own
    assumption and would look better than it is.
    """
    # S311: a seeded generator is the requirement here, not a weakness — a recovery
    # study is only evidence if it reproduces exactly from its seed.
    rng = random.Random(seed)  # noqa: S311
    decay = math.exp(-reversion_rate * dt)
    if reversion_rate > 0.0:
        stationary = volatility * math.sqrt((1.0 - decay**2) / (2.0 * reversion_rate))
    else:
        stationary = volatility * math.sqrt(dt)
    ell = initial_log_odds
    path = [ell]
    for _ in range(steps):
        ell = level + (ell - level) * decay + rng.gauss(0.0, stationary)
        path.append(ell)
    return _record(path, _uniform_times(steps, dt), seed=seed)


def fit_diffusion(trajectory: BeliefTrajectory) -> DiffusionFit:
    """Maximum-likelihood drift and volatility, tolerating unequal gaps.

    Drift is total displacement over total time; volatility comes from the
    residual increments standardised by their own gap, so a path sampled
    irregularly is not silently mis-scaled.
    """
    increments = trajectory.increments()
    gaps = trajectory.intervals()
    total_time = math.fsum(gaps)
    drift = math.fsum(increments) / total_time
    residual_sq = math.fsum(
        (increment - drift * gap) ** 2 / gap
        for increment, gap in zip(increments, gaps, strict=True)
    )
    volatility = math.sqrt(residual_sq / len(increments))
    return DiffusionFit(drift=drift, volatility=volatility, observations=len(increments))


def fit_ornstein_uhlenbeck(trajectory: BeliefTrajectory) -> OrnsteinUhlenbeckFit:
    """Least-squares OU fit via the Euler form of the drift.

    `Δl = theta·m·dt - theta·l·dt + noise` is linear in two coefficients, so the
    package's own Householder least squares does the work and the parameters
    come back by division. This is the standard discretisation bias: `theta` is
    attenuated as `dt` grows, which the recovery study measures rather than
    hides.
    """
    increments = trajectory.increments()
    gaps = trajectory.intervals()
    levels = trajectory.log_odds_path()[:-1]
    design = [[gap, level * gap] for level, gap in zip(levels, gaps, strict=True)]
    intercept, slope = solve_least_squares(design, list(increments))
    reversion_rate = -slope
    if abs(slope) < 1e-12:
        # No detectable pull: the driftless walk is the honest reading, and the
        # level is unidentified rather than zero.
        level = statistics.fmean(levels)
        reversion_rate = 0.0
    else:
        level = -intercept / slope
    residual_sq = math.fsum(
        (increment - (intercept * gap + slope * lev * gap)) ** 2 / gap
        for increment, lev, gap in zip(increments, levels, gaps, strict=True)
    )
    volatility = math.sqrt(residual_sq / len(increments))
    return OrnsteinUhlenbeckFit(
        reversion_rate=reversion_rate,
        level=level,
        volatility=volatility,
        observations=len(increments),
    )


# ---------------------------------------------------------------------------
# 4. Jump-diffusion
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class JumpDiffusionFit:
    """A diffusion plus discrete revisions, separated by robust thresholding."""

    drift: float
    volatility: float
    jump_intensity: float
    jump_mean: float
    jump_scale: float
    jump_indices: tuple[int, ...]
    observations: int

    @property
    def jump_count(self) -> int:
        return len(self.jump_indices)


def simulate_jump_diffusion(
    *,
    drift: float,
    volatility: float,
    jump_intensity: float,
    jump_mean: float,
    jump_scale: float,
    steps: int,
    dt: float,
    seed: int,
    initial_log_odds: float = 0.0,
) -> BeliefTrajectory:
    """Brownian belief interrupted by Poisson-timed discrete revisions."""
    # S311: a seeded generator is the requirement here, not a weakness — a recovery
    # study is only evidence if it reproduces exactly from its seed.
    rng = random.Random(seed)  # noqa: S311
    diffusive = volatility * math.sqrt(dt)
    jump_probability = 1.0 - math.exp(-jump_intensity * dt)
    ell = initial_log_odds
    path = [ell]
    for _ in range(steps):
        ell = ell + drift * dt + rng.gauss(0.0, diffusive)
        if rng.random() < jump_probability:
            ell = ell + rng.gauss(jump_mean, jump_scale)
        path.append(ell)
    return _record(path, _uniform_times(steps, dt), seed=seed)


def fit_jump_diffusion(
    trajectory: BeliefTrajectory, *, threshold: float = JUMP_THRESHOLD
) -> JumpDiffusionFit:
    """Separate jumps from diffusion by a robust scale, then fit each part.

    The scale comes from the median absolute deviation rather than the standard
    deviation, because the jumps are exactly what would inflate an SD-based
    threshold and hide themselves. With no jumps flagged, this reduces to
    :func:`fit_diffusion` and reports a zero intensity.
    """
    increments = trajectory.increments()
    gaps = trajectory.intervals()
    standardised = [
        increment / math.sqrt(gap) for increment, gap in zip(increments, gaps, strict=True)
    ]
    centre = statistics.median(standardised)
    deviations = [abs(value - centre) for value in standardised]
    mad = statistics.median(deviations)
    # 1.4826 makes the MAD a consistent estimator of sigma for Gaussian data.
    robust_scale = 1.4826 * mad
    if robust_scale <= 0.0:
        robust_scale = statistics.pstdev(standardised) or 1.0

    jump_indices = tuple(
        index
        for index, value in enumerate(standardised)
        if abs(value - centre) > threshold * robust_scale
    )
    jump_set = set(jump_indices)

    diffusive = [
        (increment, gap)
        for index, (increment, gap) in enumerate(zip(increments, gaps, strict=True))
        if index not in jump_set
    ]
    if not diffusive:
        raise ValueError("every increment was flagged as a jump; nothing left to fit")
    diffusive_time = math.fsum(gap for _, gap in diffusive)
    drift = math.fsum(increment for increment, _ in diffusive) / diffusive_time
    residual_sq = math.fsum((increment - drift * gap) ** 2 / gap for increment, gap in diffusive)
    volatility = math.sqrt(residual_sq / len(diffusive))

    total_time = math.fsum(gaps)
    intensity = len(jump_indices) / total_time
    if jump_indices:
        sizes = [increments[index] - drift * gaps[index] for index in jump_indices]
        jump_mean = statistics.fmean(sizes)
        jump_scale = statistics.pstdev(sizes) if len(sizes) > 1 else 0.0
    else:
        jump_mean = 0.0
        jump_scale = 0.0

    return JumpDiffusionFit(
        drift=drift,
        volatility=volatility,
        jump_intensity=intensity,
        jump_mean=jump_mean,
        jump_scale=jump_scale,
        jump_indices=jump_indices,
        observations=len(increments),
    )


# ---------------------------------------------------------------------------
# The recovery study
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ParameterRecovery:
    """How one parameter's estimate behaved across replications."""

    name: str
    truth: float
    estimates: tuple[float, ...]

    @property
    def mean_estimate(self) -> float:
        return statistics.fmean(self.estimates)

    @property
    def bias(self) -> float:
        """Mean estimate minus truth. Signed, so direction is readable."""
        return self.mean_estimate - self.truth

    @property
    def spread(self) -> float:
        return statistics.pstdev(self.estimates) if len(self.estimates) > 1 else 0.0

    @property
    def root_mean_square_error(self) -> float:
        return math.sqrt(statistics.fmean([(value - self.truth) ** 2 for value in self.estimates]))

    @property
    def relative_bias(self) -> float:
        """Bias as a fraction of truth. Infinite when the truth is zero."""
        if self.truth == 0.0:
            return math.inf if self.bias != 0.0 else 0.0
        return self.bias / abs(self.truth)


@dataclass(frozen=True, slots=True)
class RecoveryReport:
    """The result of simulating at known parameters and fitting them back.

    Deliberately carries no verdict. Whether a bias of 0.03 is acceptable is a
    protocol question, and G3 has not been passed, so this reports and stops.
    """

    model: str
    replications: int
    steps: int
    dt: float
    parameters: tuple[ParameterRecovery, ...]

    def by_name(self, name: str) -> ParameterRecovery:
        for recovery in self.parameters:
            if recovery.name == name:
                return recovery
        raise KeyError(name)

    def worst_relative_bias(self) -> float:
        return max(abs(p.relative_bias) for p in self.parameters)

    def render(self) -> str:
        lines = [
            f"recovery: {self.model}",
            f"  {self.replications} replications, {self.steps} steps, dt={self.dt}",
        ]
        for recovery in self.parameters:
            lines.append(
                f"  {recovery.name:>16}  truth {recovery.truth:+.4f}  "
                f"mean {recovery.mean_estimate:+.4f}  bias {recovery.bias:+.4f}  "
                f"rmse {recovery.root_mean_square_error:.4f}"
            )
        return "\n".join(lines)


def recovery_study(
    model: str,
    *,
    replications: int = 200,
    steps: int = 400,
    dt: float = 0.05,
    seed: int = 20260825,
    **truth: float,
) -> RecoveryReport:
    """Simulate at known parameters, fit, and report the recovery error.

    `model` selects one of `diffusion`, `ornstein_uhlenbeck`, or
    `jump_diffusion`; the remaining keyword arguments are that model's true
    parameters. Each replication uses a distinct derived seed, so the study is
    reproducible in full from the one `seed` given here.
    """
    if replications < 1:
        raise ValueError("a recovery study needs at least one replication")
    collected: dict[str, list[float]] = {}

    def observe(name: str, value: float) -> None:
        collected.setdefault(name, []).append(value)

    for replication in range(replications):
        run_seed = seed + replication
        if model == "diffusion":
            trajectory = simulate_diffusion(
                drift=truth["drift"],
                volatility=truth["volatility"],
                steps=steps,
                dt=dt,
                seed=run_seed,
            )
            fitted = fit_diffusion(trajectory)
            observe("drift", fitted.drift)
            observe("volatility", fitted.volatility)
        elif model == "ornstein_uhlenbeck":
            trajectory = simulate_ornstein_uhlenbeck(
                reversion_rate=truth["reversion_rate"],
                level=truth["level"],
                volatility=truth["volatility"],
                steps=steps,
                dt=dt,
                seed=run_seed,
            )
            ou = fit_ornstein_uhlenbeck(trajectory)
            observe("reversion_rate", ou.reversion_rate)
            observe("level", ou.level)
            observe("volatility", ou.volatility)
        elif model == "jump_diffusion":
            trajectory = simulate_jump_diffusion(
                drift=truth["drift"],
                volatility=truth["volatility"],
                jump_intensity=truth["jump_intensity"],
                jump_mean=truth["jump_mean"],
                jump_scale=truth["jump_scale"],
                steps=steps,
                dt=dt,
                seed=run_seed,
            )
            jd = fit_jump_diffusion(trajectory)
            observe("drift", jd.drift)
            observe("volatility", jd.volatility)
            observe("jump_intensity", jd.jump_intensity)
        else:
            raise ValueError(f"unknown model {model!r}")

    parameters = tuple(
        ParameterRecovery(name=name, truth=truth[name], estimates=tuple(values))
        for name, values in collected.items()
    )
    return RecoveryReport(
        model=model,
        replications=replications,
        steps=steps,
        dt=dt,
        parameters=parameters,
    )
